/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorAdministracionUsuarios;
import Controlador.ControladorBD;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Home A esta vista le llega la persistencia de los datos
     * por constructor
     *
     * @param usuario
     */
    boolean usuarioEsAdministrador = false;
    boolean usuarioEsMesaDeAyuda = false;
    boolean usuarioEsFinanciero = false;
    boolean usuarioEsSupervisorOperaciones = false;
    boolean usuarioEsOperador = false;

    /**
     *
     * @param textoUsuario
     * @param listaRoles
     * @param textoRoles
     * @throws SQLException
     */
    public PantallaPrincipal(String textoUsuario, LinkedList<String> listaRoles, String textoRoles) throws SQLException {
        initComponents();
        desaparecerMenues();
        configurarTextosUsuario(textoUsuario, textoRoles);
        habilitarMenu(listaRoles);
        setLocationRelativeTo(null);

    }

    // Habilito menúes según los roles del usuario que inició sesión.
    private void habilitarMenu(LinkedList<String> listaRoles) {
        if (listaRoles.contains("Administrador")) {
            usuarioEsAdministrador = true;
            botonConfiguracionSistema.setVisible(true);
            botonGestionUsuarios.setVisible(true);
        }

        if (listaRoles.contains("Mesa de Ayuda")) {
            usuarioEsMesaDeAyuda = true;
            botonGestionUsuarios.setVisible(true);
        }

        if (listaRoles.contains("Financiero")) {
            usuarioEsFinanciero = true;
            botonSistemaContable.setVisible(true);
        }

        if (listaRoles.contains("Supervisor Operaciones")) {
            usuarioEsSupervisorOperaciones = true;
            botonGestionOperadores.setVisible(true);
        }

        if (listaRoles.contains("Operador")) {
            usuarioEsOperador = true;
            botonOperaciones.setVisible(true);
        }
    }

    // Imprimo en la ventana de pantalla principal el nombre de usuario y sus roles
    private void configurarTextosUsuario(String textoUsuario, String textoRoles) {
        labelUsuario.setText(textoUsuario);
        labelRoles.setText(textoRoles);
    }

    // Función para ocultar todos los menú al inicio de la clase.
    // Luego los voy a iniciar dependiendo de los roles del Usuario logueado.
    private void desaparecerMenues() {
        botonConfiguracionSistema.setVisible(false);
        botonGestionUsuarios.setVisible(false);
        botonSistemaContable.setVisible(false);
        botonGestionOperadores.setVisible(false);
        botonOperaciones.setVisible(false);
    }

    private PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelRoles = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        botonConfiguracionSistema = new javax.swing.JButton();
        botonSistemaContable = new javax.swing.JButton();
        botonGestionOperadores = new javax.swing.JButton();
        botonOperaciones = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botonCerrarSesion = new javax.swing.JButton();
        botonGestionUsuarios = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario:");

        labelRoles.setText("roles");

        jLabel2.setText("Roles:");

        labelUsuario.setText("usuario");

        botonConfiguracionSistema.setText("Configuración del Sistema");
        botonConfiguracionSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfiguracionSistemaActionPerformed(evt);
            }
        });

        botonSistemaContable.setText("Sistema Contable");
        botonSistemaContable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSistemaContableActionPerformed(evt);
            }
        });

        botonGestionOperadores.setText("Gestón de Operadores");
        botonGestionOperadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionOperadoresActionPerformed(evt);
            }
        });

        botonOperaciones.setText("Operaciones");
        botonOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOperacionesActionPerformed(evt);
            }
        });

        botonCerrarSesion.setText("Cerrar Sesión");
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addComponent(botonCerrarSesion))
        );

        botonGestionUsuarios.setText("Gestión de Usuarios");
        botonGestionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionUsuariosActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRoles)
                    .addComponent(labelUsuario)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonGestionUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonGestionOperadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonSistemaContable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonConfiguracionSistema, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelUsuario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelRoles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonOperaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonSistemaContable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonGestionOperadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonGestionUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonConfiguracionSistema)
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionUsuariosActionPerformed
        // Este botón está disponible para los roles Administrador y Mesa de Ayuda
        PantallaAdministracionUsuarios gestionUsuarios = null;
        try {
            gestionUsuarios = new PantallaAdministracionUsuarios();
        } catch (SQLException ex) {
            Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        gestionUsuarios.setVisible(true);
    }//GEN-LAST:event_botonGestionUsuariosActionPerformed

    private void botonConfiguracionSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfiguracionSistemaActionPerformed
        JOptionPane.showMessageDialog(this,
                "Este botón está disponible para el rol Administrador.",
                "Información",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botonConfiguracionSistemaActionPerformed

    private void botonGestionOperadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionOperadoresActionPerformed
        JOptionPane.showMessageDialog(this,
                "Este botón está disponible para el rol Supervisor de Operaciones.",
                "Información",
                JOptionPane.INFORMATION_MESSAGE);    }//GEN-LAST:event_botonGestionOperadoresActionPerformed

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed

        PantallaInicioSesion pantallaInicial = new PantallaInicioSesion();
        pantallaInicial.setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    private void botonSistemaContableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSistemaContableActionPerformed
        JOptionPane.showMessageDialog(this,
                "Este botón está disponible para el rol Financiero.",
                "Información",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botonSistemaContableActionPerformed

    private void botonOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOperacionesActionPerformed
        JOptionPane.showMessageDialog(this,
                "Este botón está disponible para el rol Operador.",
                "Información",
                JOptionPane.INFORMATION_MESSAGE);    }//GEN-LAST:event_botonOperacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonConfiguracionSistema;
    private javax.swing.JButton botonGestionOperadores;
    private javax.swing.JButton botonGestionUsuarios;
    private javax.swing.JButton botonOperaciones;
    private javax.swing.JButton botonSistemaContable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelRoles;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables
}
